---
abstract: 'Labeled Bell Separated Value manipulator'
author:
  - 'HIROSE Masaaki <hirose31@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-LBSV
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Project::Libs: 0
  Tie::IxHash: 0
  UNIVERSAL::require: 0
  YAML::Tiny::Color: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hirose31/perl-Text-LBSV.git
version: 0.05
